### ISSUE TITLE
Unnecessary flame/framework dependency

### ISSUE THREAD

**Issue by fmasa** [seberm/nette-paypal#11]
Why does package require `flame/framework`? AFAIK it doesn't use any class from FW. Should I make PR?

**Comment by seberm** [comment]
Yes please. You can remove all "Flame" things - especially change the namespaces to something else.

What about just removing "Flame"? For example:
Change "Flame\PayPal\API" to "PayPal\API" ? Or... do you have some better idea?

Thanks a lot!

**Comment by fmasa** [comment]
`PayPal\API` seems like bad practice to me - top level namespace should match developer/team's name.

We should stick to `vendor\PackageName` format. The question is whether to use your nickname `seberm\PayPal` or to come up with something new.

**Comment by seberm** [comment]
Agree. "Seberm" sounds good :).
