### ISSUE TITLE
Composer does not download all the necessary files

### ISSUE THREAD

**Issue by temistokles** [seberm/nette-paypal#16]
Discussion (Czech) at:
https://forum.nette.org/cs/23805-paypal-komponenta-nenalezeno

What happens: necessary files are missing (e.g. class Seberm\DI\PayPalExtension). Composer download is incomplete.

**Comment by temistokles** [comment]
Source code downloaded directly from Github works fine.

**Comment by seberm** [comment]
Hello, thanks for opening a ticket. I responded to nette forum.

Component is not stable and needs some fixes. As soon as I release new version, everything should work as expected.

For now I recommend using developer (master) version and stay updated. I am going to work on it in following days.

**Comment by temistokles** [comment]
Thank you, this fixed the issue :).
