### ISSUE TITLE
Dependencies update and php version

### ISSUE THREAD

**Issue by fmasa** [seberm/nette-paypal#19]
Right now there are no real dependencies in composer.json altough this extension require at least nette/component-model. We should those deps.

Also minimal required PHP version is 5.3 which is not supported anymore ([just like 5.4](http://php.net/supported-versions.php)). Shouldn't we make a step forward and update PHP dependency to 5.5 maybe even 5.6?

**Comment by seberm** [comment]
updated:
[https://github.com/seberm/nette-paypal/commit/5179be126624be40259b24a940d2111b41780223](https://github.com/seberm/nette-paypal/commit/5179be126624be40259b24a940d2111b41780223)
Thanks!
